### ISSUE TITLE
how can i install node-gyp by complie the node-gyp code

### ISSUE THREAD

**Issue by fubh** [nodejs/node-gyp#1035]
my env can't connect to internet。so i must compile the code to install node-gyp.

can somebody tell me

**Comment by bnoordhuis** [comment]
You don't need to install node-gyp separately because it is bundled with npm and node but I assume you are talking about the source tarball it tries to download?  You can download it manually, copy it to your machine, then point node-gyp (or npm) to it with the --tarball switch.

If anything is not working, please include the exact steps you took and the terminal output.

**Comment by fubh** [comment]
@bnoordhuis thanks, you're correct,i download the nodejs resource code to resolve my problem.
