### ISSUE TITLE
Read IOJS_ORG_MIRROR and NODEJS_ORG_MIRROR also from npm config

### ISSUE THREAD

**Issue by fsmaia** [nodejs/node-gyp#1070]
Just like in [node-sass](https://github.com/sass/node-sass/blob/master/lib/extensions.js#L223), would be nice to read both `IOJS_ORG_MIRROR` and `NODEJS_ORG_MIRROR` (and their deprecated version) also from `npm config` settings. With this would be also possible to set its value in .npmrc file.

The change is really easy to do: just insert these variables in their respectives [if/else chains](https://github.com/nodejs/node-gyp/blob/master/lib/process-release.js#L66):
- `process.env.npm_config_iojs_org_mirror`
- `process.env.npm_config_nvm_iojs_org_mirror`
- `process.env.npm_config_nodejs_org_mirror`
- `process.env.npm_config_nvm_nodejs_org_mirror`

I can do a pull request if you will.

Thanks in advance!

**Comment by jvale** [comment]
Is there any appetite to include this change? Or is there any other way to go around this issue? We have build boxes that have restricted internet access and should pull the headers from an internal source, and being able to specify `NODEJS_ORG_MIRROR` from the `.npmrc` instead of an environment variable file would make our lives quite a bit easier.

**Comment by rvagg** [comment]
I'd +1 a pull request to make this happen, it just needs someone to do it. We've done away with the IOJS_ and NVM_ ones so it's much simpler now in the latest master.
