### ISSUE TITLE
Passing options from npm install

### ISSUE THREAD

**Issue by willm** [nodejs/node-gyp#1073]
Hi,

I am working within a coorporate environment which requires me to  download the node headers from a different location (not behind a proxy) it seems like the `--dist-url=$url` option would be perfect for this, however, node-gyp is being run from a dependency of mine so I don't control the arguments that get passed to it. Is there a way to pass arguments from `npm install` through to node-gyp processes spawned by dependencies?

**Comment by gibfahn** [comment]
@willm If you put the headers in the place `node-gyp` expects them to be for your platform, then they should just get picked up (`node-gyp` will use the existing ones instead of downloading). The easiest way would be to run `node-gyp configure` on your other machine, look at where the [tarball](https://nodejs.org/dist/v6.9.2/node-v6.9.2-headers.tar.gz) gets extracted to, and duplicate that on the other machine.

For me it's `~/.node-gyp/6.9.2`, which contains the `include` directory from the tarball and a file called `installVersion` (which has contents `9`).

**Comment by willm** [comment]
Thanks @gibfahn that worked a charm, I'm running in docker so I ended up adding this to my dockerfile:

```
RUN curl -sSo /usr/local/lib/node-v6.9.1-headers.tar.gz 'http://dml-eu.bpweb.bp.com/artifactory/remote-nodejs/v6.9.1/node-v6.9.1-headers.tar.gz'
RUN mkdir -p /root/.node-gyp
RUN tar xf /usr/local/lib/node-v6.9.1-headers.tar.gz -C /root/.node-gyp
RUN echo 9 > /root/.node-gyp/6.9.1/installVersion
```

What does the version file refer to? I'm just wondering on how to keep it up to date as versions of node change.

**Comment by gibfahn** [comment]
@willm I'm not sure, but it doesn't seem to have changed much:

```bash
➜  .node-gyp for i in *; do echo $i; cat $i/installVersion; done
0.10.48
9
4.6.1
9
6.6.0
9
6.7.0
9
7.1.0
9
```

It [seems to be hardcoded into node-gyp](https://github.com/nodejs/node-gyp/blob/ddac34899147e159a664a4828bfc2be3a55df8b0/package.json#L15), wouldn't worry too much about it changing. You can always just run `node-gyp configure` on your network connected machine if you want to check though.

**Comment by willm** [comment]
OK great thanks, closing the issue.
