### ISSUE TITLE
Problem building native node-sass extension on windows 10 64bit

### ISSUE THREAD

**Issue by bemon** [nodejs/node-gyp#1168]
I tried to build node-sass but I still get error
```
gyp verb validating download checksum for win-x64/node.lib (6b725cdeac99bc9574a46ee0a468fb08d6fae69f7cbd69569c3e442a85b28220 == 6b725cdeac99bc9574a46ee0a468fb08d6fae69f7cbd69569c3e442a85b28220)
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 32-bit node.lib
```

Clearly its trying to build 32bit node-sass but node v8 doesnt have 32bit builds on theirs servers.

```
gyp http 404 https://nodejs.org/download/nightly/v8.0.0-nightly20170405491d59da84/win-x86/node.lib
```
Any suggestions ?
I have 64bit node & windows installation.

Related issue on node-sass: https://github.com/sass/node-sass/issues/1945#issuecomment-293101351

**Comment by bnoordhuis** [comment]
Might have been a fluke, perhaps there was some kind of network outage since it's complaining about a failed checksum.

If you are reporting issues against nightly builds, make sure you use the latest one.

**Comment by joaocgreis** [comment]
This does not happen only for node-sass, node-gyp is broken on Windows for the v8.x nightlies because of https://github.com/nodejs/build/issues/669 . Node-gyp downloads both x86 and x64 lib files, and fails because x86 does not exist.

However, that issue was just fixed in https://github.com/nodejs/node/pull/12184 , the next nightly version should already work.
