### ISSUE TITLE
Question : Need Help to build addons using node-gyp

### ISSUE THREAD

**Issue by prajaktakul** [nodejs/node-gyp#1289]
I am new to node.js and node add-on development. 
But with the help of instructions given at github I have created one node add-on. 
The add-on successfully built and created file with .node extension. Also I am able to access functions from add-on in node.js script.

Now when I copied this built add-on on other system and tried to access through script I got following error:

```js
D:\node-addon>node server 
module.js:597 
  return process.dlopen(module, path._makeLong(filename)); 
                 ^
Error: The specified module could not be found. 
\\?\D:\node-addon\addon\build\Release\addon.node 
    at Error (native) 
    at Object.Module._extensions..node (module.js:597:18) 
    at Module.load (module.js:487:32) 
    at tryModuleLoad (module.js:446:12) 
    at Function.Module._load (module.js:438:3) 
    at Module.require (module.js:497:17) 
    at require (internal/module.js:20:19) 
    at Object.<anonymous> (D:\node-addon\addon\lib\bindings.js:4:15) 
    at Module._compile (module.js:570:32) 
    at Object.Module._extensions..js (module.js:579:10)
D:\node-addon>
```

The 'addon.node' file is present at location and it works fine in system where addon is built.

So, now how can I access the node add-on that is created on different systems as node module??(without building on each system, only will copy from one system to other)

Do I need to make any changes in 'binding.gyp' file while building addon? 

Any help will be appreciated. ****
Thanks in advance.

**Comment by bnoordhuis** [comment]
Can you fill out the issue template please?

**Comment by gibfahn** [comment]
You can't compile addons on one platform and run on another, to do that you need to cross-compile, which is pretty difficult to do (see [stackoverflow](https://stackoverflow.com/questions/30340443/cross-compile-node-module-with-native-bindings-with-node-gyp) and https://github.com/nodejs/node-gyp/issues/829).

If you want to create a package that contains addons built on all platforms prepackaged up, then you might try [node-pre-gyp](https://github.com/mapbox/node-pre-gyp). If you want to build on multiple platforms from a single machine then using Docker or full VMs (e.g. with Virtualbox) might be helpful.

Otherwise just make sure you build and run on the same type of platform (e.g. if you build on x86_64 linux, then run on x86_64 Linux, make sure the platform you build on has the same or an older level of glibc).

**Comment by prajaktakul** [comment]
**@bnoordhuis**  I will try to fill issue template...

**@gibfahn** Thanks for your comment.

Actually I have built addon on windows7 x86 platform and trying to use on other system which has same specifications. Still I am getting this error. Do I need to check any other sepecifications for Windows?
