### ISSUE TITLE
Unable to link shared library

### ISSUE THREAD

**Issue by clabroche** [nodejs/node-gyp#1296]
Hello guys, 

I am trying to build a nodejs addons that uses a shared_library which I previously  built in my package (So I got a .so files in my production dir) . I am not able to make my .node work great , it seems that my library is not fully linked .

That is what ldd return from my .node executable 

```
 linux-vdso.so.1 =>  (0x00007ffff4d16000)
 libgs.so.9 => not found
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fecc7de1000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fecc7bca000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fecc7800000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fecc74f7000)
        /lib64/ld-linux-x86-64.so.2 (0x0000560a336cb000)
```

And my binding .gyp contains

``` json
{
  "targets": [
    {
      "target_name": "ghostscriptjs",
      "sources": [
        "src/ghostscript-node.cpp",
      ],
      "cflags_cc!": [
        "-fno-exceptions",
      ],
      "cflags_cc": [
        "-fpermissive",
      ],
      "link_settings": {
        "libraries": [
          "-lgs"
          ],
        'library_dirs': [
          '/home/<user>/ghostscript-js/lib/ghostscript-9.21/sobin',
        ],
      },      
      "conditions": [
        ["OS=='win'", {
          "msvs_settings": {
            "VCCLCompilerTool": {
              "ExceptionHandling": 1
            }
          },
        }],
        ["OS=='mac'", {
          "OTHER_CPLUSPLUSFLAGS" : [ "-std=c++11", "-stdlib=libc++" ],
          "OTHER_LDFLAGS": [ "-stdlib=libc++" ],
          "xcode_settings": {
           "GCC_ENABLE_CPP_EXCEPTIONS": "YES",
           "GCC_ENABLE_CPP_RTTI": "YES",
           "MACOSX_DEPLOYMENT_TARGET": "10.12",
           "CLANG_CXX_LANGUAGE_STANDARD": "c++11"
          }
        }]
      ],
      "include_dirs": [
        "<!(node -e \"require('nan')\")",
        "lib/ghostscript-9.21/base",
        "lib/ghostscript-9.21/psi",
        "lib/ghostscript-9.21/sobin",
        "lib/ghostscript-9.21/"
      ],
      "direct_dependent_settings": {
        "include_dirs": [
          "ghostscript-9.21/base",
          "ghostscript-9.21/psi",
          "lib/ghostscript-9.21/sobin",
          "ghostscript-9.21/",
          "overrides/<(OS)/<(target_arch)/"
        ]
      }
    },
    {
      "target_name": "action_after_build",
      "type": "none",
      "dependencies": [ "<(module_name)" ]
    }
  ]
}
```

Regards

**Comment by bnoordhuis** [comment]
`'library_dirs'` should not be inside the `'link_settings'` block.

**Comment by clabroche** [comment]
I have this error:  when i test my .node: 
`Error: libgs.so.9: cannot open shared object file: No such file or directory`

And with ldd: 
`libgs.so.9 => not found`

I have now this options in my binding.gyp:
``` json
"libraries": [
        '-L/home/<user>/ghostscript-js/lib/ghostscript-9.21/sobin',
        "-lgs"
        ],
```

**Comment by bnoordhuis** [comment]
Set LD_LIBRARY_PATH in the environment (at run-time) or link the add-on with `-Wl,-rpath,/path/to/lib.so`.

**Comment by clabroche** [comment]
Thanks, it seems to be working: 
`(RPATH) Bibliothèque rpath: [/home/<user>/ghostscript-js/lib/ghostscript-9.21/sobin/libgs.so]`

But when when execute the .node we have:
`/bin/node: symbol lookup error: undefined symbol: gsapi_new_instance`

Surprising when I move my .so to /usr/lib , my .node is working, so why it's not working when setting rpath to the local path ?

Thanks by advance

**Comment by bnoordhuis** [comment]
Hard to say, could be a bunch of reasons.  Maybe your system's dynamic linker is configured to only look in certain directories.  It could just as well be something else though.

**Comment by clabroche** [comment]
OK, thanks for your help ! I close this issue.

**Comment by nehasharan** [comment]
How to link a static library while creating a shared_library using gyp? I am using below code but it is throwing linking error.
'targets': [
{
'target_name': 'abc',
'type': 'shared_library',
'conditions': [],
'dependencies': [],
'libraries':[
'mylib.a'
],
'mac_framework_dirs' : [
],
'all_dependent_settings': {},
},

**Comment by Fulguritude** [comment]
I had a similar problem (on a Linux platform), which I resolved using `patchelf`. In a nutshell, I had a 4 .so libraries, all provided locally; 2 were direct dependencies of my `binding.node` target, and 2 were indirectly called as dependencies of one of the former libraries.
What happened is when generating the `.so` libraries, they had some linking problems (caused by moving them around), which in turn made `binding.node` inherit those linking problems. Ie, `-Wl,-rpath=...` only worked for the direct dependencies of my target, but not the indirect one, which it still needed.

What fixed my issue was calling:

`patchelf --replace-needed "current_name_of_indirect_lib.so" "path/to/indirect/lib.so" direct_lib.so`

Where `current_name_of_indirect_lib` is the name for the missing/broken/not found dependency given by `ldd direct_lib.so`. The quotes are necessary for `patchelf` it seems. I used the same command on `binding.node` rather than `direct_lib.so`, as well, for the libraries that needed direct linking.

But this did not suffice to fix the indirect dependencies for `binding.node`, and `--replace-needed` did nothing for these indirect dependencies (which I could see with `ldd`) so I forced them to become direct dependencies:

`patchelf --add-needed "path/to/indirect/lib.so" binding.node`

And this fixed my issue. This method provides an alternative to using LD_LIBRARY_PATH, which did work, but wasn't acceptable for our distribution needs. Hope this helps someone else someday :)
