### ISSUE TITLE
node-gyp depends on old rimraf, causing warnings about node >= 7.0

### ISSUE THREAD

**Issue by gunsch** [nodejs/node-gyp#1307]
`node -v`: v6.9.1
`npm -v`: 3.10.8

When running `npm install` on a package containing `node-gyp`, we see the following warning:

```npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.```

It seems this is coming in from `node-gyp` -> `rimraf@2` -> `graceful-fs@1.2.3`:

```
$ npm ls graceful-fs
myproject-http@0.1.0 /usr/local/home/gunsch/myproject
├─┬ @google-cloud/datastore@1.1.0
│ └─┬ @google-cloud/common-grpc@0.4.1
│   └─┬ grpc@1.6.0
│     └─┬ node-pre-gyp@0.6.36
│       └─┬ tar@2.2.1
│         └─┬ fstream@1.0.11
│           └── graceful-fs@4.1.11
├─┬ karma@1.7.1
│ └── graceful-fs@4.1.11
├─┬ node-sass@4.5.3
│ └─┬ node-gyp@3.6.2
│   └─┬ rimraf@2.1.4
│     └── graceful-fs@1.2.3
└── UNMET PEER DEPENDENCY webpack@3.6.0
```

`rimraf` removed its `graceful-fs` dependency in `v2.2.5` (Dec 2013) and has more recently reached `v2.6.0`. Is `node-gyp` willing to upgrade its `rimraf` dependency?

**Comment by bnoordhuis** [comment]
I'm not sure why your install picks `rimraf@2.1.4` but the reason that node-gyp depends on `rimraf@2` instead of a more specific version is so we can piggy-back on (and dedupe with) the rimraf that is bundled with npm.

I suppose we could depend on `rimraf@^2.5.4`, that being the version that is bundled with npm 2.15 which in turn is bundled with node.js v4.x, but like I said, I'm not sure why your project doesn't pick up something more recent than 2.1.4.  Could it be it's satisfied from npm's on-disk cache?

**Comment by gunsch** [comment]
I tracked down the issue by bisecting our `package.json` dependencies. It ended up actually being from `angular2-template-loader@0.5.0 -> codecov -> ... -> rimraf@2.1.4`, but `npm ls` was attributing it to `node-gyp` when using our project's overall `package.json`. Sorry for the noise here.
