### ISSUE TITLE
My solution of fixing the node-gyp rebuild failed issue on MacOS 

### ISSUE THREAD

**Issue by davidchencontract** [nodejs/node-gyp#1692]
my OS is the MAC  MoJave 10.14.3
My node version is :10.15.1
my npm version is 6.9.0

I run these steps to fix the node-gyp rebuild failed issue on MacOS 
Step1:  Delete the node
sudo rm -rf ~/.node-gyp

Step2: reinstall the latest node-gyp 
sudo npm i node-gyp -g

Step3 : delete the current project nodemodules folder
sudo rm -rf ./myproject/node_modules

Step4:  reinstall in my current project
 sudo npm i -d --unsafe-perm

Then, no any fail errors on my environment!

**Comment by okwme** [comment]
doesn't work for me

**Comment by rvagg** [comment]
>  sudo npm i node-gyp -g

probably don't do this unless you're using `node-gyp` directly or are prepared to get messy with `npm config set node_gyp`, but I wouldn't recommend that because it can leave you in an awkward state in the future.

> sudo npm i -d --unsafe-perm
Avoid this _if at all possible_, you're giving `sudo` access to install scripts in whatever random dependencies are getting pulled in on your project. There's really no good reason to be doing this in your home directory. Drop the `sudo` and `--unsafe-perm`.

If it fails, first look at whether it might be the responsibility of an addon author—most of the time errors coming out of node-gyp are because the addon is not compatible with the version of Node you're using. Go chase that down first. After you've eliminated that, come back here and open up an issue with verbose output so we can see what's up and maybe someone here can help (no guarantees, most of us are volunteers).
