### ISSUE TITLE
Consider replacing `request` package

### ISSUE THREAD

**Issue by SimonSchick** [nodejs/node-gyp#1707]
* **Node Version**: *
* **Platform**: *
* **Compiler**: *
* **Module**: *

You might want to consider replacing `request` as it's entering maintenance mode.
https://github.com/request/request/issues/3142
https://github.com/request/request/issues/3143

After a first look it should be relatively easy to replace `request` with the built-in `https` library.

**Comment by bnoordhuis** [comment]
Replacing request has been suggested before in a different context but as long as npm still depends on request, we're likely to keep doing so as well.

node-gyp is normally distributed along with npm and they share a copy of request. That's good because it keeps the download size down.

Thanks for the suggestion though!
