### ISSUE TITLE
using win32 resource in addon on windows

### ISSUE THREAD

**Issue by xbqian** [nodejs/node-gyp#1744]
Hi there:
  I'm using vs2015 to build a addon, and the resource cannot be loaded. For exampe, win32 API LoadString() is used for get a static string from resource file. So i use GetModuleHandle() to get the instance handle. But is doesn't work(error : 1814, error msg : The specified resource name cannot be found in the image file.)
 Is there other way to get the instance handle for win32 APIs?

**Comment by rvagg** [comment]
sorry we haven't been able to provide an answer here @xbqian, I hope you managed to figure it out and move forward. I'm going to close this due to staleness but feel free to open a new issue with more details, perhaps even some code. The lack of details tends to be the reason these general questions go unanswered.
