### ISSUE TITLE
Require the addon created using require.resolve

### ISSUE THREAD

**Issue by FadyQJ** [nodejs/node-gyp#1914]
I am using nan and node-gyp and compiled a C++ addon, which I am loading inside an electron app.

At first I was using `require('bindings')('myLibrary')` which worked in both debug and release builds.

Now, I am forced to use `process.dlopen(module,` require.resolve('library'), os.constants.dlopen.RTLD_NOW | os.constants.dlopen.RTLD_GLOBAL)` because I have to include the global flags. But now I am unable to resolve the module directory.

I can use require.resolve('absolute/path/to/lib.node') which works but is not recommended.
And I am not able to find any documentation to understand how require.resolve and bindings work together. Any help would be appreciated!

**Comment by rvagg** [comment]
OK, so I gather from this that you're not using `bindings` now because you've decided you need to pass  because you want to pass `RTLD_NOW` and `RTLD_GLOBAL` to `dlopen()`, right?

A few comments on your questions:

1. Are you _sure_ you need to do a custom `dlopen()`, it'd be good to avoid that if you can. Maybe your use-case necessitates those flags but be sure that that's true.
2. `require.resolve()` is a perfectly reasonable API to use for this kind of thing, it's quite common in fact. It uses the same mechanics as `require()` to find files to load so isn't anything out of the ordinary. It does exactly the same steps as `require()` but stops short of the _loading_ step, instead returning you a string path to the file, which is quite handy. The reason it might be a problem with addons is that you're not guaranteed that the `addon.node` file is in the `build/Release` directory, it could be in `build/Debug`, which is basically all that `bindings` is giving you (plus some now unnecessary legacy stuff). You could be testing that yourself if you want.
3. `bindings` is probably still useful if you're sure you need a custom `dlopen()`. It has an undocumented mode that will get it to return the path, like `require.resolve()` (which it uses under the hood). Instead of `require('bindings')('myLibrary')`, try this: `const myLibraryPath = require('bindings')({ bindings: 'myLibrary', path: true })` and you'll magically get a `string` in `myLibraryPath` that you can use for your custom `dlopen()`.

I hope that helps.

**Comment by FadyQJ** [comment]
Thanks for your answer,
Late reply but I got busy with a few things.

The thing is the `RTLD_GLOBAL` and `RTLD_NOW` flags are vital to my app (on linkup dist which I am currently developing my app on)
I have used your solution which is `require('bindings')({ bindings: 'myLibrary', path: true })` and later on used load `process.dlopen(module, require.resolve(path), os.constants.dlopen.RTLD_NOW | os.constants.dlopen.RTLD_GLOBAL)`

But I still receive the following error:
`
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Could not locate the bindings file. Tried:
 → /tmp/.mount_main-1PUmjnD/resources/app.asar/build/myLibrary.node
 → /tmp/.mount_main-1PUmjnD/resources/app.asar/build/Debug/myLibrary.node
 → /tmp/.mount_main-1PUmjnD/resources/app.asar/build/Release/myLibrary.node
 → /tmp/.mount_main-1PUmjnD/resources/app.asar/out/Debug/myLibrary.node
 → /tmp/.mount_main-1PUmjnD/resources/app.asar/Debug/myLibrary.node
 → /tmp/.mount_main-1PUmjnD/resources/app.asar/out/Release/myLibrary.node
 → /tmp/.mount_main-1PUmjnD/resources/app.asar/Release/myLibrary.node
 → /tmp/.mount_main-1PUmjnD/resources/app.asar/build/default/myLibrary.node
 → /tmp/.mount_main-1PUmjnD/resources/app.asar/compiled/12.4.0/linux/x64/myLibrary.node
 → /tmp/.mount_main-1PUmjnD/resources/app.asar/addon-build/release/install-root/myLibrary.node
 → /tmp/.mount_main-1PUmjnD/resources/app.asar/addon-build/debug/install-root/myLibrary.node
 → /tmp/.mount_main-1PUmjnD/resources/app.asar/addon-build/default/install-root/myLibrary.node
 → /tmp/.mount_main-1PUmjnD/resources/app.asar/lib/binding/node-v73-linux-x64/myLibrary.node
    at bindings (/tmp/.mount_main-1PUmjnD/resources/app.asar/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/tmp/.mount_main-1PUmjnD/resources/app.asar/src/api/editor.js:4:31)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/tmp/.mount_main-1PUmjnD/resources/app.asar/src/api/api.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
`

I extracted the app.asar file located in the "linux-unpacked" directory and found that the .node file does not exist.
However, the .node file exists under "linux-unpacked\resources\build\Release\myLibrary.node"

So it seems I'm missing some argument to build the addon. If so, what is it? I am using electron-builder and not electron-rebuild (if I remember correctly with electron-rebuild I was able to load the addon using require('bindings')('myLibrary')

If this is a problem with electron-builder then I'll ask there.
Thank you for your time :)
