### ISSUE TITLE
Support for MinGW/Cygwin as an alternative to Visual Studio

### ISSUE THREAD

**Issue by mcandre** [nodejs/node-gyp#194]
node-gyp just needs `make` and `gcc`, which are provided by MinGW/Cygwin.

Is MinGW/Cygwin a viable option for node-gyp users instead of the colossal Visual Studio environment?

**Comment by smaudet** [comment]
Quick note on this, with some modification I was able to get node-gyp to generate make files in msys...this involved three things:

1) Installing node-gyp inside the mingw-based nodejs (inside of msys)
2) Patching the globally installed versions of **node-gyp/lib/build.js** and **node-gyp/lib/configure.js** in msys to set **win = false** instead of **win = process.platform === 'win32'**
3) Cleaning up the binding.gyp file in the particular package I was using (node-sass@4.5.3) and a recursed src/libsass.gyp file, to remove references to MSVS_VERSION that were causing a gyp runtime failure.
4) Issuing a node-gyp configure command.

The above appeared to generate what seem to be appropriate build files in build, however I have not figured out quite how to run them, or if they are complete:

1) **node-gyp build** runs
2) make complains about an issue:

binding.target.mk:87: *** target pattern contains no '%'.  Stop.
