### ISSUE TITLE
Installing Windows tools hangs after installing Python 2

### ISSUE THREAD

**Issue by taimoorgit** [nodejs/node-gyp#1974]
Attempted to do: 
`C:\Windows\system32>npm install --global --production windows-build-tools`
Since I cannot install `expo-cli` because of errors from `node-gyp`. 

```
C:\Windows\system32>npm --version
6.12.0

C:\Windows\system32>node -v
v12.13.0
```

OS: Windows 10 Pro, latest build.

It seems like my laptop fans are still running but no progress has been made after installing Python 2, even after 20 minutes.

![image](https://user-images.githubusercontent.com/37668804/69264623-ae44d280-0b95-11ea-9bec-e915289ce298.png)

**Comment by joaocgreis** [comment]
@taimoorgit it is normal for Visual Studio to take a long time to install, but your log clearly says that another installation is running and you should try again. I recommend making sure all Windows updates are installed and rebooting your computer before trying again.

I'll close this issue here, if you have more issues running `windows-build-tools` please open an issue in https://github.com/felixrieseberg/windows-build-tools.
