### ISSUE TITLE
fatal error: 'utility' file not found, node-gyp rebuild is failing

### ISSUE THREAD

**Issue by PrabhuPuredla95** [nodejs/node-gyp#2020]
1 warning and 1 error generated.
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/name/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/Users/name/.nvm/versions/node/v6.9.5/bin/node" "/Users/name/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/name/projects/project/node_modules/contextify
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
npm ERR! Darwin 19.2.0
npm ERR! argv "/Users/name/.nvm/versions/node/v6.9.5/bin/node" "/Users/name/.nvm/versions/node/v6.9.5/bin/npm" "install" "contextify@0.1.15"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs contextify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/name/projects/myproject/npm-debug.log

**Comment by PrabhuPuredla95** [comment]
My osx version: 10.15.2
I have tried as mentioned in this also: https://github.com/ProjectOpenSea/opensea-creatures/issues/5#issuecomment-458894627

**Comment by rvagg** [comment]
I don't see the error in here, perhaps you missed pasting something in. Regardless, two things stand out here: (1) you're using a very old version of Node.js and you really should update because we can't continue providing support for versions of Node.js that are no longer maintained and addon authors are in the same boat (the oldest supported version of Node.js today is 10) and (2) 'contextify' was moved in to Node core even longer ago, so whatever you're trying to build must be quite old and probably needs to be updated to use newer Node.js and newer APIs. As you can see, it hasn't been touched in some time and is both archived and carries a disclaimer: https://github.com/brianmcd/contextify
