### ISSUE TITLE
platformio-ide-terminal failed installation on Atom

### ISSUE THREAD

**Issue by matteogithub94** [nodejs/node-gyp#2042]
I'm trying to install the package "platformio-ide-terminal" for Atom but I have this error. Any solutions?
 
node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install C:\Users\matteo\AppData\Local\Temp\apm-install-dir-12018-9520-cjnf11.7uhdq\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js

C:\Users\matteo\AppData\Local\Temp\apm-install-dir-12018-9520-cjnf11.7uhdq\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch>if not defined npm_config_node_gyp (node "C:\Users\matteo\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\matteo\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Compilazione dei progetti nella soluzione uno alla volta. Per abilitare la compilazione parallela, aggiungere l'opzione "/m".
C:\Users\matteo\AppData\Local\Temp\apm-install-dir-12018-9520-cjnf11.7uhdq\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty.vcxproj(20,3): error MSB4019: progetto importato "C:\Microsoft.Cpp.Default.props" non trovato. Verificare che il percorso nella dichiarazione <Import> sia corretto e che il file sia presente sul disco.
C:\Users\matteo\AppData\Local\Temp\apm-install-dir-12018-9520-cjnf11.7uhdq\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty_console_list.vcxproj(20,3): error MSB4019: progetto importato "C:\Microsoft.Cpp.Default.props" non trovato. Verificare che il percorso nella dichiarazione <Import> sia corretto e che il file sia presente sul disco.
C:\Users\matteo\AppData\Local\Temp\apm-install-dir-12018-9520-cjnf11.7uhdq\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty.vcxproj(20,3): error MSB4019: progetto importato "C:\Microsoft.Cpp.Default.props" non trovato. Verificare che il percorso nella dichiarazione <Import> sia corretto e che il file sia presente sul disco.
C:\Users\matteo\AppData\Local\Temp\apm-install-dir-12018-9520-cjnf11.7uhdq\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj(20,3): error MSB4019: progetto importato "C:\Microsoft.Cpp.Default.props" non trovato. Verificare che il percorso nella dichiarazione <Import> sia corretto e che il file sia presente sul disco.

prebuild-install WARN install unexpected end of file
gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\matteo\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Users\\matteo\\AppData\\Local\\atom\\app-1.43.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\matteo\\AppData\\Local\\atom\\app-1.43.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\matteo\AppData\Local\Temp\apm-install-dir-12018-9520-cjnf11.7uhdq\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\matteo\AppData\Local\Temp\apm-install-dir-12018-9520-cjnf11.7uhdq\package.json'
npm WARN apm-install-dir-12018-9520-cjnf11.7uhdq No description
npm WARN apm-install-dir-12018-9520-cjnf11.7uhdq No repository field.
npm WARN apm-install-dir-12018-9520-cjnf11.7uhdq No README data
npm WARN apm-install-dir-12018-9520-cjnf11.7uhdq No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\matteo\.atom\.apm\_logs\2020-02-08T22_20_11_659Z-debug.log

**Comment by Thiedent** [comment]
I have the same installation failure error relating to the message "if not defined npm_config_node_gyp", after having successfully running npm install for a project on both a MAC and WINDOWS system, multiple times with no issue, yesterday both the machines starting throwing this same issue.
I had not changed anything about my system or the projects, only simply reinstalled them.

The package it stalls at for me is utf-8-validate.

This is the message that is the same as matteogithub94

> utf-8-validate@5.0.1 install c:\browser-laptop\node_modules\utf-8-validate
> node-gyp-build


c:\browser-laptop\node_modules\utf-8-validate>if not defined npm_config_node_gyp
 (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_mo
dules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\browser-laptop\node_mo
dules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  validation.c
c:\browser-laptop\node_modules\utf-8-validate\src\validation.c(2): fatal error
C1083: Cannot open include file: 'node_api.h': No such file or directory [c:\br
owser-laptop\node_modules\utf-8-validate\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Commu
nity\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\browser-laptop\node_modules\node-g
yp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:197:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\browser-laptop\\node
_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\browser-laptop\node_modules\utf-8-validate
gyp ERR! node -v v8.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

While the error code C1083 is different, i have also had the codes MSB4019 and MSB8020 come up. 

I know the code C1083 is caused by out of date node headers which do not have the node_api.h. But using newer headers that overcome this error only create a further, lengthier chain of errors.

I must stress that both my MAC and WIN environments are setup correctly and that this issue is only a day old at best. While the issues on my WIN system may appear to be related to VS and VS build tools related configuration problems, i know that this is not the case. I wonder whether since it only changed on a reinstall whether its some dependancy of a dependancy that has been updated and thus broken it.

Like op i would very much appreciate any help.

**Comment by joaocgreis** [comment]
@matteogithub94 from what I can tell from that log, you need to have Visual Studio installed to compile native code included in the module.

You are using a very old version of Node.js v10 which, among other problems, doesn't support recent versions of Visual Studio and doesn't print helpful messages when errors happen finding Visual Studio. I strongly recommend updating to the latest v10: https://nodejs.org/download/release/latest-v10.x/ .

Please follow the instructions on https://github.com/nodejs/node-gyp#on-windows to install Python and Visual Studio. Note that if you don't upgrade Node.js, you have to install Python 2 instead.

**Comment by matteogithub94** [comment]
thanks for help. But I'm using Node.js v12.16.0.

**Comment by cclauss** [comment]
Above it says...
> gyp ERR! node -v v10.2.1
> gyp ERR! node-gyp -v v3.7.0
