### ISSUE TITLE
Inconsistent "latest" npm version flips between 5.* and 6.*

### ISSUE THREAD

**Issue by ChrisHSandN** [nodejs/node-gyp#2147]
https://www.npmjs.com/package/node-gyp
Lists `5.1.1` as "latest" (and no next or beta etc..)

The last time I updated my dependencies (in early Feb 2020) I got version `6.1.0`, now when I run `npm-outdated` it is saying I need to ~~upgrade~~ downgrade to `5.1.1` to get the latest.

Which version is even the latest one we should be using?

**Comment by rvagg** [comment]
I'm sorry, this is my fault. Every time you publish it sets that version as `latest` unless you tell it not to, and because we're still maintaining 5.x it occasionally flips because I forget about this! I've set it to 6.x and this is the one you should be using. 5.x is basically the same but prefers python2 over python3 where both exist, so it's safe enough, just not ideal. 7.x will be out soon and that will be our new preferred.
