### ISSUE TITLE
Silence curl for macOS Catalina acid test

### ISSUE THREAD

**Issue by weiliddat** [nodejs/node-gyp#2148]
* **Node Version**: N/A
* **Platform**: macOS Catalina
* **Compiler**: N/A
* **Module**: N/A

This is a really small request to add the `-s` argument for the [macOS Catalina acid test](https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md#the-acid-test) to reduce noise

```shell
curl -sL https://github.com/nodejs/node-gyp/raw/master/macOS_Catalina_acid_test.sh | bash
```

Output of the original
```shell
$ curl -L https://github.com/nodejs/node-gyp/raw/master/macOS_Catalina_acid_test.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   150  100   150    0     0   1293      0 --:--:-- --:--:-- --:--:--  1282
100   495  100   495    0     0   1265      0 --:--:-- --:--:-- --:--:--  1265
Command Line Tools version: 11.5.0.0.1.1588476445
```

Output of the silenced version
```shell
$ curl -sL https://github.com/nodejs/node-gyp/raw/master/macOS_Catalina_acid_test.sh | bash
Command Line Tools version: 11.5.0.0.1.1588476445
```

**Comment by rvagg** [comment]
Yeah, I did think about asking for that when the PR was merged but I always prefer more verbosity for things like `curl|bash` that make some people uncomfortable. Although a `set -x` in the script would probably do a more helpful job on that!

Open a PR against the instructions to add the `s` if you like, I'll +1 it.

**Comment by weiliddat** [comment]
Yeah I get that too. `set -x` would help, or maybe just a `echo "Disclaimer about this being downloaded from the Internet"`?

**Comment by rvagg** [comment]
Nah, I don't think that's necessary. I'm personally _not_ concerned about the security of this `curl|bash` because (a) we control it and (b) it's over https from a trusted site. It's just that a lot of programmers have been programmed to think `curl|bash` is inherently evil and is an indicator of bad security attitudes. But there's really nothing to be done about that other than be firm when people show up with criticism.
For now let's go with the `s` in the `curl`
