### ISSUE TITLE
How to add libraries on a node addon.

### ISSUE THREAD

**Issue by lukaswilkeer** [nodejs/node-gyp#2188]
I'm attempt to create  a node addon that uses the a json cpp library. I'm attempted to use libraries(referenced on #328 ) as include dir, event the including directly but the build fails on locating the package.

Here's my gyp file.

```json
{
    "targets": [
        {
            "target_name": "bindings",
            "sources": ["analyzer.cc"]
        },
    ],
    "include_dirs": [
    	"lib/nlohmann"
    ],
    "libraries": [
    	"-lnlohmann", "-L/home/lukaswilkeer/Documents/dev/nodejs/stock-parser/lib/nlohmann"
    ]
}
 ```

What to do and how to do?

**Comment by rvagg** [comment]
Try doing a `-l<absolite path to library file>`, this is not an ideal arrangement but sometimes you don't have much choice to link to an absolute location. An ideal would be to have multiple targets and link them together. See https://github.com/Level/leveldown/blob/master/binding.gyp for how this might be done if you have control over  the library you're linking against - that one links against a `"dependency"` which has its own .gyp file, and that dependency even links against another dependency which also has its own .gyp file. So if you're bundling some C++ and publishing as a Node addon and you expect users to compile both the library and your addon wrapper then try and get it into a state where it can all be compiled with GYP and linked together by GYP rather than this manual linking arrangement.
