### ISSUE TITLE
consider release-please to improve release process

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/node-gyp#2286]
https://github.com/google-github-actions/release-please-action It's has been using in `gyp-next` and works pretty great so far as I observed (https://github.com/nodejs/gyp-next/blob/master/.github/workflows/release-please.yml
). 

Maybe it's also good here too.

@rvagg What do you think ? 

cc @targos @richardlau

**Comment by rvagg** [comment]
Maybe, I'm not totally opposed to it. What we're doing now doesn't scale very well because it's basically coming down to me managing the releases.

_But_ the install base of node-gyp is very large. 6M weekly downloads. And it's in critical path in CI systems for a very large number of installs. So we have security and stability concerns that should give us pause. And this is all outside of npm where they at least have some stability gating when pulling node-gyp in. So my concern would be the ease with which releases can be made and pushed into people's production pipelines. The write-access on this repo is fairly broad right now because we can gate releases with npm write access.

**Comment by targos** [comment]
GitHub Actions now have environment protection rules and environment secrets: https://github.blog/changelog/2020-12-15-github-actions-environments-environment-protection-rules-and-environment-secrets-beta/
Maybe that can be used to protect an npm token and only allow a subset of collaborators to publish the package?

**Comment by gengjiawen** [comment]
> The write-access on this repo is fairly broad right now because we can gate releases with npm write access.

Maybe only use it for changelog generate and release PR. remove npm publish step from the workflow.

**Comment by rvagg** [comment]
> Maybe only use it for changelog generate and release PR. remove npm publish step from the workflow.

yes, I was thinking that this might be a good way to get started, gate publish on a human for now and see how we go.

I'd be ok with exploring this switch, it'll help with getting things merged and maintaining a changelog, but we're all going to have to be educated in the commit message pattern (I'm not _quite_ there yet but have been trying to adopt it in other projects). We're clearly not scaling by sticking with the clean merge patterns and metadata of nodejs/node.

**Comment by DeeDeeG** [comment]
@rvagg here is a similar thing to `release-please-action`... but producing the Node style of CHANGELOG formatting, and working well with Node-style commit prefixes (`lib:`, `doc:`, `gyp:`, and so on) rather than conventional commits prefixes (`chore:`, `fix:`, `feat:`): [workflow.yml](https://github.com/DeeDeeG/node-gyp/blob/9fbccb181d732b5be09c1ef120642548c0288a05/.github/workflows/new-workflow.yml)

It is a GitHub Actions workflow that automatically opens a pull request with an updated `CHANGELOG.md` (and a bumped version in `package.json` also).

The PR updates each time `master` branch is pushed to, if there is anything to add to the CHANGELOG since the last release. It indirectly relies on PR labels (such as `semver-major` or `semver-minor`) via [`changelog-maker`](https://github.com/nodejs/changelog-maker), to try to guess if the proposed version bump should be patch, minor, or major. The PR management is done by the [`peter-evans/create-pull-request`](https://github.com/peter-evans/create-pull-request) GitHub Action.

It's still kind of messy, and the script is unnecessarily long, but that could be improved. (I was hoping to know if this approach is interesting to maintainers here before going all-out polishing it up.)

It works for me, example PR: https://github.com/DeeDeeG/node-gyp/pull/3

**Comment by rvagg** [comment]
One of the problems we have now is that the metadata requirements of the nodejs/node style is too onerous for other people to interact with unless they're experienced in nodejs/node landing or could use `git node land` to manage it all. The paths ahead I see are:

1. Have more people here who can deal with this process manually (hasn't been working or scaling)
2. Get the `git-node` tools working for this repo (maybe they already do? maybe that'd be easy?) and then documenting it as a process for landing commits here
3. Switch to an alternative process that doesn't rely on this metadata that people find so difficult. Which is an approach that I thought had some merit since there exists a world of tooling out there surrounding conventional-changelog style and so many people are used to using it so it's not a huge leap if you come contributing here.

**Comment by owl-from-hogvarts** [comment]
Silly question, what metadata do we rely on now?

**Comment by rvagg** [comment]
`PR-URL: <url to PR>` and `Reviewed-By: <person>`. The `PR-URL` one is consumed by changelog-maker and the other is a hold-over from requiring at least one review. If you lean into GitHub then you get both of these things from their API, and I think that's probably acceptable for this project.

**Comment by owl-from-hogvarts** [comment]
@rvagg thanks for fast replay) is this metadata required in every commit of PR or only for first/Last?

**Comment by DeeDeeG** [comment]
I made `git-node land` usable here with a few minor tweaks. See https://github.com/nodejs/node-core-utils/pull/546.

On the other hand, I'm still working on a clean switch to `release-please`, so folks here can decide between two working options.
