### ISSUE TITLE
node-gyp is infuriating

### ISSUE THREAD

**Issue by ensemblebd** [nodejs/node-gyp#2287]
No matter what OS I install this on, no matter what repo, no matter what version of Node or NPM, this product ALWAYS breaks and destroys all mental logic with comparison to a working install on another machine.

This isn't a bug report, just a **unsolid** complaint. Close/Delete as preferred...

I KNOW it's user error. I know it's not concretely, specifically, your fault.  I KNOW it's due to folder permissions, dependency chain discrepancies, node and npm version changes, lack of build tools, vendor product not properly referencing dependency versions that are uptodate with NPM version,  etc , **etc, etc, etc.**... But jesus baby in the freaking manger save me from node-gyp daily. 
I regret writing this already but how else can one express it. 

GO ahead i dare you to clone a repo to a different machine and run `npm install`. I dare you! I dare me.

**Comment by cclauss** [comment]
@ensemblebd We feel your pain.  Node-gyp is open source so please help us to improve it in any areas that are frustrating you.  One way that you could help would be to create GitHub Actions that fail.  Pull requests that put Actions into https://github.com/nodejs/node-gyp/tree/master/.github/workflows would give the community shared demonstration of failures that could be fixed.  You can pick Linux, macOS, or Windows and install any package or repo.  If we have a public working demonstration of failure then we can work to fix it.

**Comment by ensemblebd** [comment]
sorry on the rant, i know it was 100% unnecessary and uncalled for. Just been a day.

**Comment by cclauss** [comment]
Understood.  Node Sass is deprecated in favor of Dart Saas and we have so many issues on that package that we have a [Node Sass --> Dart Sass label](https://github.com/nodejs/node-gyp/issues?q=label%3A%22Node+Sass+--%3E+Dart+Sass%22).  We have [four pages of issues mentioning `bcrypt](https://github.com/nodejs/node-gyp/issues?q=bcrypt) so we could probably have a label there too.

Public demonstrations of failure are super helpful and GitHub Actions is a great way way of creating them.  Your active participation can help us to improve.

**Comment by rvagg** [comment]
@ensemblebd the dirty little secret is that _we all hate it too_ but are stuck with it for legacy reasons and because nobody has spent the time on coming up with a better solution - or the ecosystem hasn't coalesced on an alternative yet at least.

But, if you spend enough time with cross-platform build tools, these same kinds of issues come up again and again and a lot of it revolves around communicating clearly to the user what the nature of the problem is. Projects like CMake have to put in a lot of effort on that front to paper over the difficulties. We just don't have the developer-hours available to us to invest in a product that we didn't invent in the first place. We're stuck with Google's abandonware.
