### ISSUE TITLE
Document how to contribute to node-gyp's wiki

### ISSUE THREAD

**Issue by owl-from-hogvarts** [nodejs/node-gyp#2435]
If someone wants to contribute to node-gyp wiki, how it should be done? Unfortunatly, github doesn't provide any prefered way for this.

Quick googling resulting to this: https://gist.github.com/larrybotha/10650410

So i think that link may be added to `CONTRIBUTION.md` to provide explicit and unified way to contribute to wiki

**Comment by rvagg** [comment]
@owl-from-hogvarts the wiki kind of sucks because it's out-of-sight out-of-mind, and yet it's a valuable resource for people.

How about we fix it by importing the docs into this repo itself and allowing editing via PR? We could have a docs/ directory that initially pulls in the Wiki docs and leaves tombstones on each of those pages pointing to the new content.

Anyone else got thoughts on this?

**Comment by owl-from-hogvarts** [comment]
As I understand, you, @rvagg, suggesting to move whole documentation to `docs/` folder and in wiki leave references to the actual files in `docs/` folder where the documentation will be stored? If so, I am encourage it!

**Comment by rvagg** [comment]
See https://github.com/nodejs/node-gyp/pull/2440

**Comment by owl-from-hogvarts** [comment]
Can i close this issue as it seems that it is resolved)
