### ISSUE TITLE
7.1.2 version: CWE-78 : OS Command Injection in update-gyp.py:45

### ISSUE THREAD

**Issue by elcreator** [nodejs/node-gyp#2461]
update-gyp.py:45
subprocess.check_output(["git", "commit", "-m", "gyp: update gyp to " + args.tag])

Scanners as Veracode says it's CWE as args.tag is not sanitized

**Comment by cclauss** [comment]
What is the todo?  How should [`args.tag`](https://github.com/nodejs/node-gyp/blob/master/update-gyp.py#L46) be sanitized?

**Comment by elcreator** [comment]
It just says
`Validate all untrusted input to ensure that it conforms to the expected format, using centralized data validation routines when possible. When using black lists, be sure that the sanitizing routine performs a sufficient number of iterations to remove all instances of disallowed characters. Most APIs that execute system commands also have a "safe" version of the method that takes an array of strings as input rather than a single string, which protects against some forms of command injection.`

**Comment by rvagg** [comment]
This is a utility for internal use only, manually by people who know what it does, it's not expected to be used by anyone else so sanitisation hasn't been considered important. If you have a suggestion for changing this to fix whatever is giving you this flag then a pull request will probably be fine, otherwise I think you're just going to have to live with it.

**Comment by cclauss** [comment]
I think we close.  This command already implements the `array of strings` approach recommended above.  The `args.tag` can not change which command is run (`git commit -m`) but can only effect the second part of the commit message.
