### ISSUE TITLE
Potential risk: External Control of File Name or Path

### ISSUE THREAD

**Issue by kerenren** [nodejs/node-gyp#2466]
Source code: 
https://github.com/nodejs/node-gyp/blob/4d036526c5347ad6fb0394993bda05f8260f7ae4/gyp/test_gyp.py#L78

Description: This call to os.chdir() contains a path manipulation flaw. The argument to the function is a filename constructed using user-supplied input. If an attacker is allowed to specify all or part of the filename, it may be possible to gain unauthorized access to files on the server, including those outside the webroot, that would be normally be inaccessible to end users. The level of exposure depends on the effectiveness of input validation routines, if any.

Remediation: Validate all user-supplied input to ensure that it conforms to the expected format, using centralized data validation routines when possible. When using blocklists, be sure that the sanitizing routine performs a sufficient number of iterations to remove all instances of disallowed characters.

References: [CWE](http://cwe.mitre.org/data/definitions/73.html) [WASC](http://projects.webappsec.org/w/page/13246952/Path%20Traversal)

**Comment by rvagg** [comment]
please take it up with https://github.com/nodejs/gyp-next (or get a more intelligent code scanning tool)

c'mon, seriously, this is a test file, what is this tool you're using?

**Comment by kerenren** [comment]
I reported the bug in case it's relevant.  sorry for the bugs. Veracode was the scanning tool.  It generates several Very high/ Medium errors related to node-gyp module.

**Comment by rvagg** [comment]
@kerenren I appreciate the desire to be helpful, unfortunately, most code scanning tools are blunt instruments that generate a lot of cruft that are not helpful without further human inspection. Reports like the ones you've filed are fairly common but really not helpful unless they are accompanied by some interpretation that suggests that they are anything more than standard code scanning tool cruft.

We can participate in the game of _make the code scanning tool stop misinterpreting things_ by tweaking code and whatnot—for a tool like node-gyp, that game probably isn't such a bad game to play since this code is so widely distributed. But we, as maintainers, are not going to do that work ourselves because we're not using those tools and we're not impacted by their silly reports.

If you'd like to help shut your code scanner up, then we'd likely help you get some changes in to the code as long as they don't make material difference. But you're going to have to do a lot of that work. As I suggested in my messages, the changes you want to make need to go into nodejs/gyp-next instead of this repo because we just vendor in that Python code here.

Apologies for the terseness, but these copy/paste reports from mindless tools without any additional intelligent commentary can be pretty frustrating for open source maintainers.
