### ISSUE TITLE
node-gyp configure stop in http get 

### ISSUE THREAD

**Issue by timescodex** [nodejs/node-gyp#251]
Before everything was ok,but I changed to my server and execute this:

```
elearn$ node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@0.9.6
gyp info using node@0.10.6 | linux | x64
gyp http GET http://nodejs.org/dist/v0.10.6/node-v0.10.6.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.6/node-v0.10.6.tar.gz
```

and stopped here,I dont know what is the problem? Is it a bug?Or something I did wrong?

**Comment by DjebbZ** [comment]
Similar problem, sorry to bump the issue.

We're using `d3.js`, and a dependency of `d3.js` (`d3` -> `jsdom` -> `contextify`) uses `node-gyp` to compile some native module. The problem we have is that when `node-gyp` tries to download node, it doesn't pass the proxy. `npm` passes the proxy without a problem since we configured it properly, exactly as @muthunagu100 said above. So `npm install` works fine. 

As the `node-gyp rebuild` command is hardcoded in `contextify`'s package.json, I don't know how to pass the proxy option. I can't even monkey-patch the file by hand since the dependency is too deep and we're building with Jenkins, which starts the build with a fresh `npm install`.

Does anyone know how to specify a proxy for `node-gyp` when one is not able to pass the `--proxy` option ? Thanks in advance.

**Comment by DjebbZ** [comment]
I'm reading the source code of node-gyp to find whether there's a environment variable to specify the proxy...
A question : would you accept a pull request that make node-gyp use npm's proxy settings ? I may try if it doesn't involve C/C++ code.

**Comment by DjebbZ** [comment]
Ok, seems like this code already exists, in https://github.com/TooTallNate/node-gyp/blob/master/lib/install.js#L131

```
 // basic support for a proxy server
var proxyUrl = gyp.opts.proxy
             || process.env.http_proxy
             || process.env.HTTP_PROXY
             || process.env.npm_config_proxy
```

------

Ok, the problem for us was maven (through jenkins). We're using the "ant" maven plugin to launch `npm install`, and apparently it doesn't pass properly the environment to `npm`, including the proxy settings. Bypassing maven by executing `npm install` in a jenkins "pre step" solved the problem for us.

Sorry for the issue pollution. Hoping this will help someone else !
