### ISSUE TITLE
Appropriate C++ version specifications

### ISSUE THREAD

**Issue by kriszyp** [nodejs/node-gyp#2557]
* **Node Version**: 12, 14, 16, 17
* **Platform**: unix
* **Compiler**: C++ 11 & 14
* **Module**: multiple packages

This is may be less of a bug report, and more of a request for clarification of best practice using node-gyp and whether or not to specify C++ versions. I maintain several node-gyp based packages, and occasionally have run into bug reports dealing with C++ version issues. Specifically, I have seen a report this like this https://github.com/Venemo/node-lmdb/issues/190#issuecomment-975970238 where the add-on is apparently compiled with a version of C++ older than 14, which fails to compile V8 (headers) in Node v16+ (which requires C++ version 14+) with `error: ‘remove_cv_t’ is not a member of ‘std’`, but compiles successfully with `-std=c++14` explicitly specified. On the other hand, I have seen reports of a build (prebuild) for Node v14- that was compiled with `-std=c++14` (Node v14-'s V8 only requires C++ version 11) causing a runtime load failure https://github.com/DoctorEvidence/lmdb-js/issues/46, and only working if compiled with C++ version 11.

My question is: is it appropriate for node add-on packages to be specifying a `-std=c++14` or `-std=c++11` flag in binding.gyp (under `cflags_cc`) for compiling V8? It certainly makes sense to specify this if the add-on itself is using newer features, but for simply compiling V8 headers, I would have thought that node-gyp itself would/should be handling the appropriate C++ version? Or perhaps it is, and maybe there are some extraneous issue at play (99.99% of the time, _not_ specifying -std=C++X seems to do the right thing). Specifying this flag is particularly challenging, because I don't know of any way to set up this flag as conditional based on the node abi version that is being compiled (I know how to get the currently _executed_ node version, but that's not necessarily the same as the node abi that is being targeted, especially during compilation of prebuilds). Anyway, there is probably something I am misunderstanding, so apologies if I missing something obvious here, but if you have any guidance, appreciate it, thank you!

**Comment by rvagg** [comment]
Hello again @kriszyp!

So the best practice is probably something like: leave it alone unless your own code is using C++ features that break your own compiling with the lowest version of Node.js that you want to support. So if you're using C++14 features, then you'll probably need to add that flag in. Otherwise you're best off leaving it alone and letting the default handle it.

That second issue you linked @ https://github.com/DoctorEvidence/lmdb-js/issues/46 is a good illustration of the linking problems, and it's not so much about what Node.js is compiled with, but what your addon is compiled with. The base OS where the addon is being loaded doesn't have a new enough libstdc++ installed, which is the problem you'll have whenever you get ahead of the curve with C++ features, and why you're best being conservative about your choice of features.

But having said that, for the Node.js builds, we do a bit of a trick to ensure maximal compatibility with older Linux distributions even when using a newer libstdc++ and even a newer libc. The RedHat devtoolset compilers are specially constructed such that they compile binaries down to compaibility with the libraries installed by default on common RHEL systems, which tends to be quite old. It's a special case and I'm not aware of any other toolset that you can do this with. But if you can use a RHEL, or CentOS, or other system on which you can get a devtoolset installed that has a compiler new enough to support the features you want, then you can make addon binaries to ship to your users that will work even on quite old systems. We list what we use here: https://github.com/nodejs/node/blob/master/BUILDING.md#official-binary-platforms-and-toolchains

So my recommendation for anyone shipping prebuilt addons to users where you don't want to have to tell people "sorry, your distro is too old, upgrade" (nope), or "sorry, you'll need to go to .... and get a newer toolchain installed to use my binaries" (annoying, but possible), is to compile the addons on CentOS using a devtoolset gcc.

The `prebuild` ecosystem even has Docker images for this: https://github.com/prebuild/docker-images#images (I've just noticed a quote from me that echoes the above! so maybe in future I'll just point there).

I hope this helps.

**Comment by kriszyp** [comment]
@rvagg Thank you so much, this is super helpful! And yes, I have been more recently building binaries on a Centos 7 image, and seems like that has worked really well (I was asking about this just because I assume that even if I distribute binaries for all the common OS/arches, I'll never cover everything). Anyway, thank you again, I really appreciate your help and guidance and all your work!
