### ISSUE TITLE
I tried installing the dependencies with npm i, but it doesn't work !! Help me

### ISSUE THREAD

**Issue by veffev** [nodejs/node-gyp#2788]
When I try to install the project dependencies with npm I get this error:

![Schermata 2023-01-13 alle 19 04 38](https://user-images.githubusercontent.com/92869120/212389258-10e9c8f1-e27f-42aa-921a-26cb9d816b5c.png)

Anyone could help me ?

**Comment by cclauss** [comment]
When you created this issue, you deleted the text which explains the problem.

**Comment by DeeDeeG** [comment]
From the original version of your comment:

> error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?

This happens when packages specify an old C/C++ standard version in their `binding.gyp` and you try to build them with newer NodeJS or newer Electron. A _newer_ version of `node-sass` _might_ compile with recent NodeJS, or you could use an _older_ [supported LTS version of NodeJS](https://github.com/nodejs/release#release-schedule), perhaps?... But `node-sass` package is deprecated in general, so moving to a different package is much better if you can. (Particularly Dart-based `sass` npm package is the main official replacement, if I understand correctly.)

...

Explanation from here: https://github.com/nodejs/node-gyp/tree/main/docs#node-sass-is-deprecated

> ## `node-sass` is deprecated
>
> Please be aware that the package [`node-sass` is deprecated](https://github.com/sass/node-sass#node-sass) so you should actively seek alternatives.  Please avoid opening new `node-sass` issues on this repo.  You can try `npm install --global node-sass@latest` but we [cannot help much](https://github.com/nodejs/node-gyp/issues?q=is%3Aissue+label%3A%22Node+Sass+--%3E+Dart+Sass%22+) here.
