### ISSUE TITLE
ffi-nappi is not compatible with Node.js 16, 18, and 20

### ISSUE THREAD

**Issue by zghbyslzf** [nodejs/node-gyp#2889]
windows  11 

D:\work\NN-project\nn-client-all>node --version
v16.16.0

D:\work\NN-project\nn-client-all>pnpm --version
8.6.10

D:\work\NN-project\nn-client-all>npm --version
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
8.11.0

D:\work\NN-project\nn-client-all>node-gyp --version
v9.4.0

D:\work\NN-project\nn-client-all>npm list -g --depth 0
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
D:\software\nodejs -> .\
├── corepack@0.10.0
├── node-addon-api@7.0.0
├── node-gyp@9.4.0
├── npm@8.11.0
├── pnpm@8.6.10
└── windows-build-tools@

my logs

D:\work\NN-project\nn-client-all>pnpm i
Scope: all 8 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +1622
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: D:\.pnpm-store\v3
  Virtual store is at:             node_modules/.pnpm
node_modules/ffi-napi: Running install script, failed in 2.4s
node_modules/ffi-napi install$ node-gyp-build
│ D:\work\NN-project\nn-client-all\node_modules\ffi-napi>if not defined npm_config_node_gyp (node "D:\software\nvm\v16.16.0\node_modules\pnpm\dist\node-gyp-bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\software\nvm\v16.16.0\node_modules\pnpm\dist\node_module…
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@9.4.0
│ gyp info using node@16.16.0 | win32 | ia32
│ gyp info find Python using Python version 3.11.4 found at "C:\Users\zghby\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe"
│ gyp info find VS using VS2022 (17.7.33920.267) found at:
│ gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Preview"
│ gyp info find VS run with --verbose for detailed information
│ gyp info spawn C:\Users\zghby\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe
│ gyp info spawn args [
│ gyp info spawn args   'D:\\software\\nvm\\v16.16.0\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\gyp\\gyp_main.py',
│ gyp info spawn args   'binding.gyp',
│ gyp info spawn args   '-f',
│ gyp info spawn args   'msvs',
│ gyp info spawn args   '-I',
│ gyp info spawn args   'D:\\work\\NN-project\\nn-client-all\\node_modules\\ffi-napi\\build\\config.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   'D:\\software\\nvm\\v16.16.0\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\addon.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   'C:\\Users\\zghby\\AppData\\Local\\node-gyp\\Cache\\16.16.0\\include\\node\\common.gypi',
│ gyp info spawn args   '-Dlibrary=shared_library',
│ gyp info spawn args   '-Dvisibility=default',
│ gyp info spawn args   '-Dnode_root_dir=C:\\Users\\zghby\\AppData\\Local\\node-gyp\\Cache\\16.16.0',
│ gyp info spawn args   '-Dnode_gyp_dir=D:\\software\\nvm\\v16.16.0\\node_modules\\pnpm\\dist\\node_modules\\node-gyp',
│ gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\zghby\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.16.0\\\\<(target_arch)\\\\node.lib',
│ gyp info spawn args   '-Dmodule_root_dir=D:\\work\\NN-project\\nn-client-all\\node_modules\\ffi-napi',
│ gyp info spawn args   '-Dnode_engine=v8',
│ gyp info spawn args   '--depth=.',
│ gyp info spawn args   '--no-parallel',
│ gyp info spawn args   '--generator-output',
│ gyp info spawn args   'D:\\work\\NN-project\\nn-client-all\\node_modules\\ffi-napi\\build',
│ gyp info spawn args   '-Goutput_dir=.'
│ gyp info spawn args ]
│ gyp: Active code page: 65001
│ ..\node-addon-api\node_api.gyp not found (cwd: D:\work\NN-project\nn-client-all\node_modules\ffi-napi) while loading dependencies of binding.gyp while trying to load binding.gyp
│ gyp ERR! configure error
│ gyp ERR! stack Error: `gyp` failed with exit code: 1
│ gyp ERR! stack     at ChildProcess.onCpExit (D:\software\nvm\v16.16.0\node_modules\pnpm\dist\node_modules\node-gyp\lib\configure.js:325:16)
│ gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
│ gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
│ gyp ERR! System Windows_NT 10.0.22000
│ gyp ERR! command "D:\\software\\nodejs\\node.exe" "D:\\software\\nvm\\v16.16.0\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
│ gyp ERR! cwd D:\work\NN-project\nn-client-all\node_modules\ffi-napi
│ gyp ERR! node -v v16.16.0
│ gyp ERR! node-gyp -v v9.4.0
│ gyp ERR! not ok
└─ Failed in 2.4s at D:\work\NN-project\nn-client-all\node_modules\ffi-napi
Progress: resolved 0, reused 1445, downloaded 0, added 1622, done
 ELIFECYCLE  Command failed with exit code 1.

**Comment by cclauss** [comment]
This is a https://github.com/nodejs/node-gyp/labels/ffi-napi issue as demonstrated at node-ffi-napi/node-ffi-napi#255.  Please join the discussion on that repository because we cannot solve this here.

**Comment by zghbyslzf** [comment]
> 这是一个 [ ffi-napi问题，如](https://github.com/nodejs/node-gyp/labels/ffi-napi)[node-ffi-napi/node-ffi-napi#255](https://github.com/node-ffi-napi/node-ffi-napi/pull/255) 所示。请加入该存储库的讨论，因为我们无法在这里解决这个问题。
> 
> 以[node-ffi-napi/node-ffi-napi#256 的方式结束](https://github.com/node-ffi-napi/node-ffi-napi/issues/256)

PS D:\work\NN-project> node-gyp configure build
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.0
gyp info using node@16.16.0 | win32 | ia32
gyp info find Python using Python version 3.11.4 found at "C:\Users\zghby\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe"
gyp info find VS using VS2022 (17.7.33920.267) found at:
gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Preview"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\zghby\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe
gyp info spawn args [
gyp info spawn args   'D:\\software\\nvm\\v16.16.0\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\work\\NN-project\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\software\\nvm\\v16.16.0\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\zghby\\AppData\\Local\\node-gyp\\Cache\\16.16.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\zghby\\AppData\\Local\\node-gyp\\Cache\\16.16.0',
gyp info spawn args   '-Dnode_gyp_dir=D:\\software\\nvm\\v16.16.0\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\zghby\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.16.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\work\\NN-project',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\work\\NN-project\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: D:\work\NN-project) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\software\nvm\v16.16.0\node_modules\node-gyp\lib\configure.js:325:16)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.22000
gyp ERR! command "D:\\software\\nodejs\\node.exe" "D:\\software\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd D:\work\NN-project
gyp ERR! node -v v16.16.0
gyp ERR! node-gyp -v v9.4.0
gyp ERR! not ok

**Comment by zghbyslzf** [comment]
> This is a [ ffi-napi](https://github.com/nodejs/node-gyp/labels/ffi-napi) issue as demonstrated at [node-ffi-napi/node-ffi-napi#255](https://github.com/node-ffi-napi/node-ffi-napi/pull/255). Please join the discussion on that repository because we cannot solve this here.
> 
> Closing in favor of [node-ffi-napi/node-ffi-napi#256](https://github.com/node-ffi-napi/node-ffi-napi/issues/256)

My colleagues' node versions are all 16+，and do not have this bug

**Comment by zghbyslzf** [comment]
PS D:\work\test-project\node-ffi-napi-master\node-ffi-napi-master> node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.0
gyp info using node@16.16.0 | win32 | ia32
gyp info find Python using Python version 3.11.4 found at "C:\Users\zghby\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe"
gyp info find VS using VS2022 (17.7.33920.267) found at:
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'node-addon-api'
Require stack:
- D:\work\test-project\node-ffi-napi-master\node-ffi-napi-master\[eval]
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at [eval]:1:1
    at Script.runInThisContext (node:vm:129:12)
    at Object.runInThisContext (node:vm:305:38)
    at node:internal/process/execution:76:19
    at [eval]-wrapper:6:22
    at evalScript (node:internal/process/execution:75:60) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\work\\test-project\\node-ffi-napi-master\\node-ffi-napi-master\\[eval]'
  ]
}
gyp: Call to 'node -p "require('node-addon-api').include"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\software\nvm\v16.16.0\node_modules\node-gyp\lib\configure.js:325:16)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.22000
gyp ERR! command "D:\\software\\nodejs\\node.exe" "D:\\software\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\work\test-project\node-ffi-napi-master\node-ffi-napi-master
gyp ERR! node -v v16.16.0
gyp ERR! node-gyp -v v9.4.0
gyp ERR! not ok

**Comment by pplmx** [comment]
<details>
<summary>ffi-napi error log</summary>

yarn install v1.22.19
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > swagger-ui-express@4.6.3" has unmet peer dependency "express@>=4.0.0 || >=5.0.0-beta".
warning " > @nestjs/testing@9.4.3" has unmet peer dependency "@nestjs/common@^9.0.0".
warning " > @nestjs/testing@9.4.3" has unmet peer dependency "@nestjs/core@^9.0.0".
warning " > ts-loader@9.4.4" has unmet peer dependency "webpack@^5.0.0".
[4/4] Building fresh packages...
[5/5] ⠈ ffi-napi
[-/5] ⠈ waiting...
[-/5] ⠈ waiting...
[-/5] ⠁ waiting...
error C:\Users\pplmx\JetBrains\IdeaProjects\mo-deploy\repos\task-executor\node_modules\ffi-napi: Command failed.
Exit code: 1
Command: node-gyp-build
Arguments:
Directory: C:\Users\pplmx\JetBrains\IdeaProjects\mo-deploy\repos\task-executor\node_modules\ffi-napi
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.0
gyp info using node@18.18.2 | win32 | x64
gyp info find Python using Python version 3.11.6 found at "C:\Users\pplmx\AppData\Local\Programs\Python\Python311\python.exe"

gyp info find VS using VS2022 (17.7.34221.43) found at:
gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\pplmx\AppData\Local\Programs\Python\Python311\python.exe
gyp info spawn args [
gyp info spawn args 'C:\\Users\\pplmx\\scoop\\persist\\nvm\\nodejs\\v18.18.2\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'msvs',
gyp info spawn args '-I',
gyp info spawn args 'C:\\Users\\pplmx\\JetBrains\\IdeaProjects\\mo-deploy\\repos\\task-executor\\node_modules\\ffi-napi\\build\\config.gypi',
gyp info spawn args '-I',
gyp info spawn args 'C:\\Users\\pplmx\\scoop\\persist\\nvm\\nodejs\\v18.18.2\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args '-I',
gyp info spawn args 'C:\\Users\\pplmx\\AppData\\Local\\node-gyp\\Cache\\18.18.2\\include\\node\\common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=C:\\Users\\pplmx\\AppData\\Local\\node-gyp\\Cache\\18.18.2',
gyp info spawn args '-Dnode_gyp_dir=C:\\Users\\pplmx\\scoop\\persist\\nvm\\nodejs\\v18.18.2\\node_modules\\node-gyp',
gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\pplmx\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\18.18.2\\\\<(target_arch)\\\\node.lib',
gyp info spawn args '-Dmodule_root_dir=C:\\Users\\pplmx\\JetBrains\\IdeaProjects\\mo-deploy\\repos\\task-executor\\node_modules\\ffi-napi',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'C:\\Users\\pplmx\\JetBrains\\IdeaProjects\\mo-deploy\\repos\\task-executor\\node_modules\\ffi-napi\\build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args 'build\\binding.sln',
gyp info spawn args '/clp:Verbosity=minimal',
gyp info spawn args '/nologo',
gyp info spawn args '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]

  nothing.c
  win_delay_load_hook.cc
  nothing.vcxproj -> C:\Users\pplmx\JetBrains\IdeaProjects\mo-deploy\repos\task-executor\node_modules\ffi-napi\build\Release\\nothing.lib
  Preprocessing assembly file ..\..\..\deps\libffi\src\x86\win64_intel.preasm
  '"call"' is not recognized as an internal or external command,
  operable program or batch file.
C:\Users\pplmx\JetBrains\IdeaProjects\mo-deploy\repos\task-executor\node_modules\ffi-napi\build\deps\libffi\ffi.targets(34,5): error MSB3721: The command "call "call" "../../../deps/libffi/preprocess_asm.cmd" "../../../deps/libffi/include" "../../../deps/libffi/config/win/x64" "..\..\..\deps\libffi\src\x86\win64_intel.preasm" "Release\obj\ffi\win64_intel.asm"" exited with code 1. [C:\Users\pplmx\JetBrains\IdeaProjects\mo-deploy\repos\task-executor\node_modules\ffi-napi\build\deps\libffi\ffi.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (C:\Users\pplmx\scoop\persist\nvm\nodejs\v18.18.2\node_modules\node-gyp\lib\build.js:209:23)
gyp ERR! stack at ChildProcess.emit (node:events:517:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:292:12)
gyp ERR! System Windows_NT 10.0.22635
gyp ERR! command "C:\\Users\\pplmx\\scoop\\apps\\nvm\\current\\nodejs\\nodejs\\node.exe" "C:\\Users\\pplmx\\scoop\\apps\\nvm\\current\\nodejs\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\pplmx\JetBrains\IdeaProjects\mo-deploy\repos\task-executor\node_modules\ffi-napi

</details>
