### ISSUE TITLE
build success , but run fail! it caused by %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by zejie** [nodejs/node-gyp#420]
window8 x64
vs2010 x64
node v0.10.26

detail:
Error: %1 is not a valid Win32 application. 
f:\space\node-client\node_modules\usb-detection\build\Release\detection.node
    at Module.load (module.js:352:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:360:17)
    at require (module.js:376:17)
    at bindings (F:\space\node-client\node_modules\usb-detection\node_modules\bindings\bindings.js:76:44)
    at Object.eval (F:\space\node-client\node_modules\usb-detection\index.js:6:38)
    at Module._compile (module.js:452:26)
    at Object.Module._extensions..js (module.js:470:10)
    at Module.load (module.js:352:32)
    at Function.Module._load (module.js:308:12)

**Comment by xhallix** [comment]
I got the same problem here

windows7 x64
node v0.10.26

bindings.js throws error in line 79 when trying to run, with the same error message

**Comment by NicholasJohn16** [comment]
I'm having this issue as well. I'm one Windows 8.1 x64 with node.js x64. Any ideas what could cause this error?

**Comment by 0x00A** [comment]
This is still a problem. My guess was that it was the wrong arch parameter, but i've tried all combinations of parameters with no success. If nothing else, this issue should get some attention for the fact that ` %1 is not a valid Win32 application.` is a terrible error message.

**Comment by rvagg** [comment]
I don't think we have any control over any of that error message. I'm not sure where `%1` is coming from but my guess it's from a .cmd or .bat somewhere. @zejie or @NicholasJohn16, how are you calling this application to get this error?

FYI this error generally comes up from having an add-on that's compiled with a different number of bits to the Node it's trying to load in to. e.g. you might have a 32-bit Node installed but you have a 64-bit add-on, or vice versa. It's kind of tricky to get this right but basically you should always try to have a Node with the right number of bits for your system, which is almost always 64-bits these days. Then node-gyp should compile your addons as 64-bit.

I'm not entirely sure but it may come from trying to load an ABI-incompatible addon to Node. This can happen if you have, for example, everything working on Node v6 and then upgrade to Node v7. This requires an addon rebuild, `npm rebuild` might help in that situation as would removing your node_modules directory and reinstalling everything.

**Comment by 0x00A** [comment]
@rvagg thanks for the notes! It'd be great if there was a canonical explanation for this error somewhere.

> `npm rebuild` might help in that situation as would removing your node_modules directory and reinstalling everything.

This is the equivalent of "turning it off and on again", but it seems like it almost always works for people. Unless you are building your own add-on...

Two weeks ago I was trying to do a build for my electron project on a 64bit Windows 10 VM. I was totally new to Windows. The message seemed broken since 1. its message looks like its missing data and 2. I'm pretty sure I downloaded all 64bit versions of everything. I didn't see the message on `leveldown` since we have pre-builds for those. But I did see it on my own native add-on, `taglib2`. My add-on stopped throwing the error when i downgraded `electron` to 32bit.

I've started doing windows builds from these VMs regularly so I'll try to find out more precisely what the issue is and make a note of it here for future visitors.
