### ISSUE TITLE
node-gyp build error when installing phonegap

### ISSUE THREAD

**Issue by Kurukshetran** [nodejs/node-gyp#503]
Below is the builderror.log
gyp ERR! Completion callback never invoked! 
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Kurukshetran\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\node_modules\socket.io\node_modules\engine.io\node_modules\ws
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.2
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     https://github.com/TooTallNate/node-gyp/issues

**Comment by Trott** [comment]
It seems like perhaps this should be closed. Feel free to re-open (or leave a comment requesting that it be re-opened) if you are still experiencing this on a currently-supported version of Node.js or if you otherwise believe this should remain open. I'm just tidying up and not acting on a super-strong opinion or anything like that.
