### ISSUE TITLE
Isn't there a way to make installation easier?

### ISSUE THREAD

**Issue by inf3rno** [nodejs/node-gyp#662]
Can't you add some binaries, which install node-gyp and the requirements automatically? Why do we have to do this manually in 2015? Why do I have to install the whole visual studio, and python tools when I don't want to use them. Can't you extract the necessary parts and add to an installer?

**Comment by CrisLi** [comment]
i have the same feeling

**Comment by TooTallNate** [comment]
One word: licensing...

**Comment by developernaren** [comment]
This is just annoying. I have to download and install a software that is more that 4 gb which I am never going to use.

**Comment by Sogl** [comment]
@developernaren, I already donwloaded more than 15GB :tired_face:

**Comment by ichadhr** [comment]
+1 I love the way ruby have [DevKit](http://rubyinstaller.org/add-ons/devkit/)

**Comment by Fishrock123** [comment]
Sorry, I'm not sure there's anything actionable for us here. :(

**Comment by inf3rno** [comment]
We ended up having the windows-build-tools anyways. :-)

**Comment by refack** [comment]
> We ended up having the windows-build-tools anyways. :-)

I have a long term goal to have a xcopyable VC tools install. The [compiler is already xcopyable](https://blogs.msdn.microsoft.com/vcblog/2016/02/16/try-out-the-latest-c-compiler-toolset-without-waiting-for-the-next-update-of-visual-studio/), python is xcopyable, only thing that still needs massaging is the SDK.
Re: @TooTallNate's licensing's comment, I have Microsoft's blessing, and anyway since they enabled silent installs all EULAs became if-you-use-you-accept.
