### ISSUE TITLE
node-gyp on remote machines

### ISSUE THREAD

**Issue by blazerguns** [nodejs/node-gyp#684]
Hi,

I installed node-gyp on my machine using "npm install -g node-gyp". This works great.
We moved our project code to server that does not have access to internet. This is a RHEL 6.6 server. How can I install node-gym without using npm which needs to download from the internet. I assume there must be a simple way to do this?

Regards,
Varun

**Comment by Fishrock123** [comment]
> I assume there must be a simple way to do this?

The best you'll get is to install node-gyp elsewhere and move the files. Or make a git clone of it and move the files over.

You'll also need to download a tarball of the node version you are using and move it over. Then setup node-gyp to use that rather than trying to fetch it from the internet, see: https://github.com/nodejs/node-gyp/blob/master/lib/node-gyp.js#L98

Let us know if you need any further help. :)
