### ISSUE TITLE
Error with Python 3.5 on Win7

### ISSUE THREAD

**Issue by justsayno** [nodejs/node-gyp#707]
Hi I get the following error when using Node GYP in both the Yeoman angular-generator and the yeoman angular-fullstack generator.

`
{lamb} if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v3.5.0, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:119:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:108:9
ERR! stack     at ChildProcess.exithandler (child_process.js:742:7)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at maybeClose (child_process.js:1015:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\dev\pp\PropertyPlot\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN optional dep failed, continuing bufferutil@1.1.0
`

I don't know exactly what this means and it appears to have no effect on the end result of the generator that is using it but thought I would log it in case no one was aware.

**Comment by rvagg** [comment]
@justsayno thanks for reporting—angular-generator or one of its dependencies is trying to compile a C++ addon to get its work done, in this case it looks like the `ws` module and also one of its dependencies, the `bufferutil` module. In order to be able to compile these addons you have to have Python 2.7 installed as 3.x is not supported by GYP. If you have both installed then I think you can set the `PYTHON` environment variable to the Python 2.6 location prior to running and it _should_ work.
