### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by drewish** [nodejs/node-gyp#769]
These links are broken:
```
 * [gyp user documentation](https://chromium.googlesource.com/external/gyp/+/master/docs/UserDocumentation.md)
 * [gyp input format reference](https://chromium.googlesource.com/external/gyp/+/master/docs/InputFormatReference.md)
```

I believe the docs have moved to:
* https://gyp.gsrc.io/docs/UserDocumentation.md
* https://gyp.gsrc.io/docs/InputFormatReference.md

But hopefully someone familiar with them could double check it.

**Comment by bchr02** [comment]
+1

**Comment by gagern** [comment]
:+1:

There are broken links in those docs as well. Note e.g. how https://gyp.gsrc.io/docs/LanguageSpecification.md refers to https://gyp.gsrc.io/docs/InputFormatReference#List_Filters.md instead of https://gyp.gsrc.io/docs/InputFormatReference.md#List_Filters. The link to https://gyp.gsrc.io/docs/InputFormatReference.md#Merge-Basics is so broken it isn't even parsed as a markdown link. Not sure where to report any of this.
