### ISSUE TITLE
ImportError: No module named gyp

### ISSUE THREAD

**Issue by ericgrosse** [nodejs/node-gyp#807]
I get the following error when running `npm install mongoose` and any other package that depends on node-gyp:

```
if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Traceback (most recent call last):
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 15, in <module>
    import gyp
ImportError: No module named gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\dev\Pluralsight\Web Development with ExpressJS\node_modules\kerberos
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

Some details about my environment:
OS: Windows 8.1
node: v4.2.2
npm: v3.3.12
python: 2.7.9

What's causing this error and how can I fix it? Googling "no module named gyp" returns very little, and the solutions I've tried didn't work. I suspect the root issue is something other than what the error is hinting at.

**Comment by bnoordhuis** [comment]
What does `C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp` and its subdirectories contain?

**Comment by ericgrosse** [comment]
Sorry for the late reply. The directory you mentioned contains the following:

![node-gyp-1](https://cloud.githubusercontent.com/assets/6740888/11386879/a9569c8c-92f3-11e5-9b5c-a7d872980c19.png)

None of the sub-directories are empty, do you need to see the contents inside of each one?

**Comment by bnoordhuis** [comment]
No, just `pylib\gyp`.

**Comment by ericgrosse** [comment]
I apologize, I reset my computer to factory settings then followed [these steps](https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245) for making node-gyp work on windows and everything works fine now. Will re-open if I ever encounter this error again because I have no idea how to reproduce it from a fresh install of Windows.

**Comment by ericgrosse** [comment]
I managed to reproduce the issue. Following the node-gyp Windows workaround [here](https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245), the command

`npm config set python python2.7`

causes all npm installs relying on node-gyp to fail with the "no module named gyp" error. The fix was to just set python using the full path to the executable, as follows:

`npm config set python C:\Python27\python.exe`

This may cause a separate error,  `The imported project "C:\Microsoft.Cpp.Default.props" was not found`. The fix for that is

`set VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140`
 
(See [here](http://stackoverflow.com/questions/21069699/node-packages-not-building-on-windows-8-1-missing-microsoft-cpp-default-props))

**Comment by Programming4life** [comment]
@ericgrosse I keep getting ``no module named gyp`` and I tried ``` npm config set python C:\Python27\python.exe ``` but it has no effect.

**Comment by Sebastien-G** [comment]
**Success installing npm bcrypt module on windows 10**

- nodejs version: 4.4.5
- npm version: 2.15.5
- bcrypt version 0.8.7

--

**System 1 (desktop)**
Windows 10 - Pro - 64 bits - FRENCH
Intel Core i7-3770 CPU @ 3.40GHz
16 GB RAM

**System 2 (laptop)**
Dell XPS 15 9550
Windows 10 - Family - 64 bits - FRENCH
Intel Core i7-6700HQ CPU @ 2.60GHz
16 GB RAM

---

_The steps I will detail here, as well as the output, are those from system 1 (but the steps were the same on system 2).
I am not claiming any of these steps are the correct ones, but they do reflect the sequence that led to a successful install of the bcrypt npm module (version 0.8.7, as of june 10, 2016)._

**STEP 1**
Perform full installation of C++ Build Tools 2015 (from: [https://blogs.msdn.microsoft.com/vcblog/2016/03/31/announcing-the-official-release-of-the-visual-c-build-tools-2015/](https://blogs.msdn.microsoft.com/vcblog/2016/03/31/announcing-the-official-release-of-the-visual-c-build-tools-2015/))
(I say full install because this is what I did, however I don't claim that the full install is necessary)
_Note:_ this may take a while as the full program is over 4GB

**STEP 2**
Install Python 2.7.11 (from: [https://www.python.org/](https://www.python.org/))
_Note:_ during installation select the "add to PATH" option (which is not selected by default)

**STEP 3**
Run: 
`npm config set msvs_version 2015 --global`
_Note:_ I ran it as administrator in Windows cmd.exe

**STEP 4**
In my NodeJS project folder (a little blog app i am writing to learn NodeJS), I then ran the install command:
`npm install bcrypt --save`

This is the output I got (********** asterisks are simply used to hide my local project folder path):

```
npm WARN package.json blog@1.0.0 No repository field.
npm WARN package.json blog@1.0.0 No README data

> bcrypt@0.8.7 install D:\**********\blog\node_modules\bcrypt
> node-gyp rebuild


D:\**********\blog\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Génération des projets individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
  blowfish.cc
  bcrypt.cc
  bcrypt_node.cc
..\src\bcrypt.cc(232): warning C4267: '=': conversion from 'size_t' to 'unsigned char', possible loss of data [D:\**********\blog\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
..\src\bcrypt_node.cc(76): warning C4244: 'argument': conversion from 'ssize_t' to 'unsigned char', possible loss of data [D:\**********\blog\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
..\src\bcrypt_node.cc(229): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [D:\**********\blog\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
..\src\bcrypt_node.cc(230): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [D:\**********\blog\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
  win_delay_load_hook.c
     Creating library D:\**********\blog\node_modules\bcrypt\build\Release\bcrypt_lib.lib and object D:\**********\blog\node_modules\bcrypt\build\Release\bcrypt_lib.exp
  Generating code
  Finished generating code
  bcrypt_lib.vcxproj -> D:\**********\blog\node_modules\bcrypt\build\Release\\bcrypt_lib.node
bcrypt@0.8.7 node_modules\bcrypt
+-- bindings@1.2.1
+-- nan@2.3.5
```

I am now able to run `bcrypt()` commands in my NodeJS app, they turn out something like:

`$2a$10$pDJX6lz6QBVatYCC.KiOJ.q6t6uAlKxRsny9tEPiSHTMhNBIhymW2`

I have no way of knowing if these hashes are perfect bcrypt hashes be they look good to me.

I would appreciate any input regarding the importance of the warning referenced in the output above.

_Thanks to all who contributed to this thread :)_

**Comment by kounkou** [comment]
Hi there!
anyone solved this issue ? Got the same thing.

**Comment by piccoloaiutante** [comment]
Me too got the same issue.

**Comment by refack** [comment]
@piccoloaiutante since you are the latest, could you provide the full output?

**Comment by axlotl** [comment]
fwiw, even though I'm doing a different thing on a different operating system (trying to build this: https://github.com/awslabs/serverless-image-resizing), I'm getting the same error, so here's some output if it's of any use:

> sharp@0.17.3 install /home/ec2-user/serverless-resize/lambda/node_modules/sharp
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/bin/gyp", line 15, in <module>
    import gyp
ImportError: No module named gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:428:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.4.37-40.44.amzn1.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ec2-user/serverless-resize/lambda/node_modules/sharp
gyp ERR! node -v v0.10.48
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0
[ec2-user@domU-12-31-39-13-D1-5D lambda]$ which gyp
/usr/bin/gyp

**Comment by refack** [comment]
@axlotl make sure you are using the latest `npm` version https://docs.npmjs.com/getting-started/installing-node (`node-gyp` is updated when `npm` is updated)

P.S. If you are using an EC2 machine, which template did you use (and which `nodejs` and `npm` do you have installed), I'll try to reproduce. To find installed versions run : `npm version`

P.P.S. I not a linux maven, but AFAIK `node-gyp` doesn't need `GYP` installed. It comes with it's own copy.
```
[ec2-user@domU-12-31-39-13-D1-5D lambda]$ which gyp
/usr/bin/gyp
```

**Comment by axlotl** [comment]
@refack thank you, npm version was exactly the problem. It was freshly installed via yum but the ec2 instance was kind of old - I kind of figured yum would always give me the latest but I was wrong. Fixed by instantiating a new instance and installing on that.

**Comment by tomasfejfar** [comment]
In my case it was caused by the fact that I had python2.7 installed via cygwin and I needed to change the npm python variable `npm config set python c:\Users\tomasfejfar\.windows-build-tools\python27\python.exe` to location specified in https://github.com/nodejs/node-gyp#on-windows

**Comment by computerquip-streamlabs** [comment]
Not to hijack this already dead thread but it's still mildly fresh. 

Python on Windows has a launcher (called `py`). Something like `npm config set python 'py -2'` works if your python installation was done through the installers. That said, this could possibly also be done through npm to find the most suitable python instead of assuming that python is python2 (since that just never seems to work out).
