### ISSUE TITLE
Headers too old with v3.2.1?

### ISSUE THREAD

**Issue by heaths** [nodejs/node-gyp#835]
I see lots of examples around the web using node-gyp for native node addons, but things they somehow accomplish are inaccessible with the headers pulled down with node-gyp v3.2.1, which appear to be node 4.2.1 headers.

For example, I get an error trying to do this, even though lots of sample code against older versions of Node support it:

``` c++
Persistent<FunctionTemplate> constructor = Persistent<FunctionTemplate>::New(FunctionTemplate::New(MyWrapper::New));
constructor->InstanceTemplate()->SetInternalFieldCount(1);
// ...
```

With the node 4.2.1 headers, the `*` and `&` operators are inaccessible.

But these projects also have dependencies on much older builds of node, so is it that the headers with node-gyp v3.2.1 are too new, or is something else wrong?

Note that I'm able to build when not using inaccessible constructs, but I need to be able to access the PrototypeTemplate of other wrapper classes. While this works with `Local<T>`, these may be GC'd later so I really need the access via `Persistent<T>`.

**Comment by bnoordhuis** [comment]
That's because the V8 API changes over time.  In your code, you need to explicitly pass the `v8::Isolate*` in the calls to `Persistent<T>::New()` and `FunctionTemplate::New()`.

If you're targeting multiple node version, you would do best to use https://www.npmjs.org/package/nan - it abstracts away most of the differences between node and V8 versions.

I'll close the issue, it's not directly related to node-gyp.

**Comment by heaths** [comment]
Thanks for the pointer. I hadn't seen mention of that project. Unfortunately, the operators are still private in their abstractions but I've logged an issue against them: https://github.com/nodejs/nan/issues/522.
