### ISSUE TITLE
Build without VS

### ISSUE THREAD

**Issue by rakeen** [nodejs/node-gyp#895]
I was wondering why do we need the VS tools to compile stuff? Can't we just build it with native g++/gcc compiler?
I understand it uses gyp(from chromium) which was actually built for generating native IDE project files(which we don't need here in node; or do we?!).

**Comment by bnoordhuis** [comment]
It's because of ABI compatibility - g++ doesn't do C++ name mangling like MS compilers do.  The binaries from https://nodejs.org/dist/ are compiled with VS so you couldn't load an add-on compiled with g++ with them.

In the future, it may be possible to build with clang++; they've being working hard towards MS ABI compatibility.

**Comment by jbergstroem** [comment]
More info about compatibility can be found here: http://clang.llvm.org/docs/MSVCCompatibility.html

**Comment by taoqf** [comment]
When could we use clang instead of vs?
